Improve protection tab and nav bar
Sulagna-Dutta-Roy/Covid19-website pull request #58
Opened 2022-08-10 05:30 UTC by w3nhuii

# Description

1. Link the protection button in navbar to the protection tab
2. Add new protection tab

Fixes:  #57

## Type of change

- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x ] I have made this from my own
- [x ] I have taken help from some online resourses 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
![Picture1](https://user-images.githubusercontent.com/100828499/183822744-e7e0952f-3bfd-4319-b7f5-3d06a8e98b83.png)

2022-08-10 16:06 UTC, Sulagna-Dutta-Roy requested changes
Kindly update the PR template from your PR. You've changed the whole template from the .github file don't do this for the next time also tick all the relevant checkboxes

2022-08-11 09:27 UTC, Sulagna-Dutta-Roy commented
Can you tell me whether you are the part of HackClub Sunmer of Code or not ???? kindly reply here

2022-08-11 11:08 UTC, w3nhuii commented
Nope. I'm not

2022-08-11 18:38 UTC, Sulagna-Dutta-Roy approved these changes

2022-08-11 18:43 UTC, merged